# Generated by Django 4.2.1 on 2023-05-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='totalcost',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='totalquantity',
            field=models.ImageField(default='11', upload_to=''),
            preserve_default=False,
        ),
    ]
