# Generated by Django 4.2.1 on 2023-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orders_totalcost_orders_totalquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='totalcost',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='totalquantity',
            field=models.IntegerField(max_length=100),
        ),
    ]
