# Generated by Django 4.2.1 on 2023-05-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_discount_price_products_carbohydrates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Minerals',
        ),
        migrations.RemoveField(
            model_name='products',
            name='vitamins',
        ),
    ]
